language:
    - java

jdk:
    - openjdk8
  
script:
    - mvn "-Dtest=org/apache/tajo/tests/*Test" -DfailIfNoTests=false clean verify
    - cat /home/travis/build/gabrielequatrana/tajo/tests/target/rat.txt